# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2517e326111af5ac4e62111b1b22b467e5b73d31d66451acd69d7ec962c864c414ba98905fbc189cbffa2ccb1b45a987e9f8a55360ebe9edefa60206d3bc496c

test:
  secret_key_base: 30f3b580988d32b67702b5af8650737020b2fed809152fcfb54fe73c3551f56785e042d2a0640dfec3cb63c38ffa3734b9ddd02fb41efdf0f2b9bbb70eca5341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
